package entities;
// Generated Feb 20, 2017 2:55:43 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Comments generated by hbm2java
 */
@Entity
@Table(name="comments"
    ,catalog="pia"
)
public class Comments  implements java.io.Serializable {


     private Integer idcomm;
     private Festivals festivals;
     private Users users;
     private String content;
     private int rating;
     private String festivalName;

    public Comments() {
    }

    public Comments(Festivals festivals, Users users, String content, int rating, String festivalName) {
       this.festivals = festivals;
       this.users = users;
       this.content = content;
       this.rating = rating;
       this.festivalName = festivalName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDComm", unique=true, nullable=false)
    public Integer getIdcomm() {
        return this.idcomm;
    }
    
    public void setIdcomm(Integer idcomm) {
        this.idcomm = idcomm;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IDFest", nullable=false)
    public Festivals getFestivals() {
        return this.festivals;
    }
    
    public void setFestivals(Festivals festivals) {
        this.festivals = festivals;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IDUser", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="content", nullable=false, length=100)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    
    @Column(name="rating", nullable=false)
    public int getRating() {
        return this.rating;
    }
    
    public void setRating(int rating) {
        this.rating = rating;
    }

    
    @Column(name="festivalName", nullable=false, length=45)
    public String getFestivalName() {
        return this.festivalName;
    }
    
    public void setFestivalName(String festivalName) {
        this.festivalName = festivalName;
    }




}


