package entities;
// Generated Feb 20, 2017 2:55:43 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Day generated by hbm2java
 */
@Entity
@Table(name="day"
    ,catalog="pia"
)
public class Day  implements java.io.Serializable {


     private Integer idday;
     private Festivals festivals;
     private Date date;
     private int totalTickets;
     private int leftTickets;

    public Day() {
    }

    public Day(Festivals festivals, Date date, int totalTickets, int leftTickets) {
       this.festivals = festivals;
       this.date = date;
       this.totalTickets = totalTickets;
       this.leftTickets = leftTickets;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDDay", unique=true, nullable=false)
    public Integer getIdday() {
        return this.idday;
    }
    
    public void setIdday(Integer idday) {
        this.idday = idday;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IDFest", nullable=false)
    public Festivals getFestivals() {
        return this.festivals;
    }
    
    public void setFestivals(Festivals festivals) {
        this.festivals = festivals;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="totalTickets", nullable=false)
    public int getTotalTickets() {
        return this.totalTickets;
    }
    
    public void setTotalTickets(int totalTickets) {
        this.totalTickets = totalTickets;
    }

    
    @Column(name="leftTickets", nullable=false)
    public int getLeftTickets() {
        return this.leftTickets;
    }
    
    public void setLeftTickets(int leftTickets) {
        this.leftTickets = leftTickets;
    }




}


