package entities;
// Generated Feb 20, 2017 2:55:43 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Festivals generated by hbm2java
 */
@Entity
@Table(name = "festivals", catalog = "pia"
)
public class Festivals implements java.io.Serializable {

    private Integer idfest;
    private String name;
    private String place;
    private Date begin;
    private Date end;
    private int priceDay;
    private int priceFestival;
    private String facebook;
    private String twitter;
    private String instagram;
    private String youtube;
    private long visited;
    private int ticketsPerUser;
    private int ticketsPerDay;
    private int totalRating;
    private int numberRatings;
    private long income;
    private Set<Users> userses = new HashSet<Users>(0);
    private Set<Messages> messageses = new HashSet<Messages>(0);
    private Set<Files> fileses = new HashSet<Files>(0);
    private Set<Day> days = new HashSet<Day>(0);
    private Set<Performers> performerses = new HashSet<Performers>(0);
    private Set<Tickets> ticketses = new HashSet<Tickets>(0);
    private Set<Comments> commentses = new HashSet<Comments>(0);

    public Festivals() {
    }

    public Festivals(String name, String place, Date begin, Date end, int priceDay, int priceFestival, long visited, int ticketsPerUser, int ticketsPerDay) {
        this.name = name;
        this.place = place;
        this.begin = begin;
        this.end = end;
        this.priceDay = priceDay;
        this.priceFestival = priceFestival;
        this.visited = visited;
        this.ticketsPerUser = ticketsPerUser;
        this.ticketsPerDay = ticketsPerDay;
    }

    public Festivals(String name, String place, Date begin, Date end, int priceDay, int priceFestival, long visited, int ticketsPerUser, int ticketsPerDay, int totalRating, int numberRatings, long income) {
        this.name = name;
        this.place = place;
        this.begin = begin;
        this.end = end;
        this.priceDay = priceDay;
        this.priceFestival = priceFestival;
        this.visited = visited;
        this.ticketsPerUser = ticketsPerUser;
        this.ticketsPerDay = ticketsPerDay;
        this.totalRating = totalRating;
        this.numberRatings = numberRatings;
        this.income = income;
    }

    public Festivals(String name, String place, Date begin, Date end, int priceDay, int priceFestival, String facebook, String twitter, String instagram, String youtube, long visited, int ticketsPerUser, int ticketsPerDay, int totalRating, int numberRatings, long income, Set<Users> userses, Set<Messages> messageses, Set<Files> fileses, Set<Day> days, Set<Performers> performerses, Set<Tickets> ticketses, Set<Comments> commentses) {
        this.name = name;
        this.place = place;
        this.begin = begin;
        this.end = end;
        this.priceDay = priceDay;
        this.priceFestival = priceFestival;
        this.facebook = facebook;
        this.twitter = twitter;
        this.instagram = instagram;
        this.youtube = youtube;
        this.visited = visited;
        this.ticketsPerUser = ticketsPerUser;
        this.ticketsPerDay = ticketsPerDay;
        this.totalRating = totalRating;
        this.numberRatings = numberRatings;
        this.income = income;
        this.userses = userses;
        this.messageses = messageses;
        this.fileses = fileses;
        this.days = days;
        this.performerses = performerses;
        this.ticketses = ticketses;
        this.commentses = commentses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "IDFest", unique = true, nullable = false)
    public Integer getIdfest() {
        return this.idfest;
    }

    public void setIdfest(Integer idfest) {
        this.idfest = idfest;
    }

    @Column(name = "name", nullable = false, length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "place", nullable = false, length = 45)
    public String getPlace() {
        return this.place;
    }

    public void setPlace(String place) {
        this.place = place;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "begin", nullable = false, length = 10)
    public Date getBegin() {
        return this.begin;
    }

    public void setBegin(Date begin) {
        this.begin = begin;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "end", nullable = false, length = 10)
    public Date getEnd() {
        return this.end;
    }

    public void setEnd(Date end) {
        this.end = end;
    }

    @Column(name = "priceDay", nullable = false)
    public int getPriceDay() {
        return this.priceDay;
    }

    public void setPriceDay(int priceDay) {
        this.priceDay = priceDay;
    }

    @Column(name = "priceFestival", nullable = false)
    public int getPriceFestival() {
        return this.priceFestival;
    }

    public void setPriceFestival(int priceFestival) {
        this.priceFestival = priceFestival;
    }

    @Column(name = "facebook", length = 100)
    public String getFacebook() {
        return this.facebook;
    }

    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }

    @Column(name = "twitter", length = 100)
    public String getTwitter() {
        return this.twitter;
    }

    public void setTwitter(String twitter) {
        this.twitter = twitter;
    }

    @Column(name = "instagram", length = 100)
    public String getInstagram() {
        return this.instagram;
    }

    public void setInstagram(String instagram) {
        this.instagram = instagram;
    }

    @Column(name = "youtube", length = 100)
    public String getYoutube() {
        return this.youtube;
    }

    public void setYoutube(String youtube) {
        this.youtube = youtube;
    }

    @Column(name = "visited", nullable = false)
    public long getVisited() {
        return this.visited;
    }

    public void setVisited(long visited) {
        this.visited = visited;
    }

    @Column(name = "ticketsPerUser", nullable = false)
    public int getTicketsPerUser() {
        return this.ticketsPerUser;
    }

    public void setTicketsPerUser(int ticketsPerUser) {
        this.ticketsPerUser = ticketsPerUser;
    }

    @Column(name = "ticketsPerDay", nullable = false)
    public int getTicketsPerDay() {
        return this.ticketsPerDay;
    }

    public void setTicketsPerDay(int ticketsPerDay) {
        this.ticketsPerDay = ticketsPerDay;
    }

    @Column(name = "totalRating", nullable = false)
    public int getTotalRating() {
        return this.totalRating;
    }

    public void setTotalRating(int totalRating) {
        this.totalRating = totalRating;
    }

    @Column(name = "numberRatings", nullable = false)
    public int getNumberRatings() {
        return this.numberRatings;
    }

    public void setNumberRatings(int numberRatings) {
        this.numberRatings = numberRatings;
    }

    @Column(name = "income", nullable = false)
    public long getIncome() {
        return this.income;
    }

    public void setIncome(long income) {
        this.income = income;
    }

    @ManyToMany(fetch = FetchType.EAGER, mappedBy = "festivalses")
    public Set<Users> getUserses() {
        return this.userses;
    }

    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "festivals")
    public Set<Messages> getMessageses() {
        return this.messageses;
    }

    public void setMessageses(Set<Messages> messageses) {
        this.messageses = messageses;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "festivals")
    public Set<Files> getFileses() {
        return this.fileses;
    }

    public void setFileses(Set<Files> fileses) {
        this.fileses = fileses;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "festivals")
    public Set<Day> getDays() {
        return this.days;
    }

    public void setDays(Set<Day> days) {
        this.days = days;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "festivals")
    public Set<Performers> getPerformerses() {
        return this.performerses;
    }

    public void setPerformerses(Set<Performers> performerses) {
        this.performerses = performerses;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "festivals")
    public Set<Tickets> getTicketses() {
        return this.ticketses;
    }

    public void setTicketses(Set<Tickets> ticketses) {
        this.ticketses = ticketses;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "festivals")
    public Set<Comments> getCommentses() {
        return this.commentses;
    }

    public void setCommentses(Set<Comments> commentses) {
        this.commentses = commentses;
    }

}
