package entities;
// Generated Feb 20, 2017 2:55:43 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Files generated by hbm2java
 */
@Entity
@Table(name="files"
    ,catalog="pia"
)
public class Files  implements java.io.Serializable {


     private Integer idfil;
     private Festivals festivals;
     private Users users;
     private String location;
     private int isVideo;
     private int isAccepted;
     private String festivalName;

    public Files() {
    }

    public Files(Festivals festivals, Users users, String location, int isVideo, int isAccepted, String festivalName) {
       this.festivals = festivals;
       this.users = users;
       this.location = location;
       this.isVideo = isVideo;
       this.isAccepted = isAccepted;
       this.festivalName = festivalName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDFil", unique=true, nullable=false)
    public Integer getIdfil() {
        return this.idfil;
    }
    
    public void setIdfil(Integer idfil) {
        this.idfil = idfil;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IDFest", nullable=false)
    public Festivals getFestivals() {
        return this.festivals;
    }
    
    public void setFestivals(Festivals festivals) {
        this.festivals = festivals;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IDUser", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="location", nullable=false, length=100)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    
    @Column(name="isVideo", nullable=false)
    public int getIsVideo() {
        return this.isVideo;
    }
    
    public void setIsVideo(int isVideo) {
        this.isVideo = isVideo;
    }

    
    @Column(name="isAccepted", nullable=false)
    public int getIsAccepted() {
        return this.isAccepted;
    }
    
    public void setIsAccepted(int isAccepted) {
        this.isAccepted = isAccepted;
    }

    
    @Column(name="festivalName", nullable=false, length=45)
    public String getFestivalName() {
        return this.festivalName;
    }
    
    public void setFestivalName(String festivalName) {
        this.festivalName = festivalName;
    }




}


