package entities;
// Generated Feb 20, 2017 2:55:43 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Loggins generated by hbm2java
 */
@Entity
@Table(name="loggins"
    ,catalog="pia"
)
public class Loggins  implements java.io.Serializable {


     private Integer idlog;
     private String username;

    public Loggins() {
    }

    public Loggins(String username) {
       this.username = username;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDLog", unique=true, nullable=false)
    public Integer getIdlog() {
        return this.idlog;
    }
    
    public void setIdlog(Integer idlog) {
        this.idlog = idlog;
    }

    
    @Column(name="username", nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }




}


