package entities;
// Generated Feb 20, 2017 2:55:43 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Messages generated by hbm2java
 */
@Entity
@Table(name="messages"
    ,catalog="pia"
)
public class Messages  implements java.io.Serializable {


     private Integer idmes;
     private Festivals festivals;
     private Users users;
     private String content;

    public Messages() {
    }

    public Messages(Festivals festivals, Users users, String content) {
       this.festivals = festivals;
       this.users = users;
       this.content = content;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDMes", unique=true, nullable=false)
    public Integer getIdmes() {
        return this.idmes;
    }
    
    public void setIdmes(Integer idmes) {
        this.idmes = idmes;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IDFest", nullable=false)
    public Festivals getFestivals() {
        return this.festivals;
    }
    
    public void setFestivals(Festivals festivals) {
        this.festivals = festivals;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IDUser", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="content", nullable=false, length=4096)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


