package entities;
// Generated Feb 20, 2017 2:55:43 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Performers generated by hbm2java
 */
@Entity
@Table(name="performers"
    ,catalog="pia"
)
public class Performers  implements java.io.Serializable {


     private Integer idper;
     private Festivals festivals;
     private String name;
     private Date start;
     private Date end;

    public Performers() {
    }

    public Performers(Festivals festivals, String name, Date start, Date end) {
       this.festivals = festivals;
       this.name = name;
       this.start = start;
       this.end = end;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDPer", unique=true, nullable=false)
    public Integer getIdper() {
        return this.idper;
    }
    
    public void setIdper(Integer idper) {
        this.idper = idper;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IDFest", nullable=false)
    public Festivals getFestivals() {
        return this.festivals;
    }
    
    public void setFestivals(Festivals festivals) {
        this.festivals = festivals;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start", nullable=false, length=19)
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end", nullable=false, length=19)
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }




}


